application: mailinator-monitor
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.+\.(png|js|css|ico))
  static_files: static/\1
  upload: static/(.+\.(png|js|css|ico))

- url: /.*
  script: router.py
